name: Run Insider CEO Strategy

on:
  workflow_dispatch:  # ✅ 手动触发
  schedule:
    - cron: "30 12 * * 1-5"  # ✅ 美东时间 08:30 触发

jobs:
  run-insider-ceo:
    runs-on: ubuntu-latest
    environment: TELEGRAM_TOKEN  # ✅ 指定环境名，匹配你设置 Secrets 的 Environment 名称

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH to include project root
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run Insider CEO Strategy
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python strategies/insider_ceo/main.py

      - name: Upload Result CSV
        uses: actions/upload-artifact@v4
        with:
          name: ceo_results_csv
          path: data/insider_ceo/*.csv

